name: Demo
on:
  push:

jobs:
  demo:
    name: Demo run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run my action
        uses: ./
        with:
          job-status: ${{ job.status }}

      - run: sleep 5
